// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktnzaoxjogmvqqnsqufo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0bnphb3hqb2dtdnFxbnNxdWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MTQ0MjksImV4cCI6MjA3ODI5MDQyOX0.v44QdxTxCCn-DfaqI90CNfn3LgvR1qERWiLLWJzo9XM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});